### ISSUE TITLE
When launching League of Legends, the message 'Cannot initialize graphics settings' appears.

### ISSUE THREAD

**Issue by galaxynote666** [dartraiden/NVIDIA-patcher#132] opened 2024-08-01 18:42 UTC
"I'm using the P106-100. Recently, after a Windows and League of Legends update, I'm getting an error message saying 'Cannot initialize graphics settings.' Is there a solution for this? I would appreciate your help. I am Korean and used a translation tool."

**Comment by operador777** [comment] 2024-08-05 18:27
Hello, greetings from Colombia! I am also using a tool to translate, so I hope you can understand the instructions. I am a frequent player of league of legends, I had the same error and this is due to the implementation of the Vanguard in the game. At the moment the solution that works for most people is to install windows 10 on a version that had not yet installed an update that blocks the drivers (security update in June 2023 (I believe it's KB5028166)) and install the Dartraiden driver.

Tell me if it works for you.

The game is working fine for me using a modified version of windows 11 called "WinterOS" and using the latest Dartraiden driver, if you want more detailed instructions, you can add me on Discord and by that means I can help you, you can find me as "k_r_a_i_t" and talk to me.

**Comment by BluePurplePro** [comment] 2024-08-06 08:45
Or just  install stock 417.22 driver, change/edit some registry and you're good to go
https://youtu.be/w3PHWJWlXgo

**Comment by galaxynote666** [comment] 2024-08-09 07:53
That seems like a really good solution. However, reinstalling Windows is too much of a hassle, so I resolved the issue with version 417.22. Thank you! And thanks to the person who mentioned version 417.22 as well.

**Comment by dartraiden** [comment] 2024-08-11 18:57
Duplicate of https://github.com/dartraiden/NVIDIA-patcher/issues/114

**Closed by dartraiden** 2024-08-11 18:57 UTC
